Added point of contact (contact person) to Dream
Midburn/dreams pull request #114
Opened 2017-01-21 17:13 UTC by basels

visible to dream-creator/admin/guide, editable by admin/guide

2017-01-21 17:17 UTC, basels commented
https://github.com/Midburn/dreams/issues/111

2017-01-21 18:37 UTC, rootux requested changes
Looks great-  added 2 comments.

2017-01-21 18:37 UTC, rootux commented on app/views/camps/show.html.erb
> +                <% if @camp.active? %>
How does the fact the the camp is active related here?

2017-01-21 18:37 UTC, rootux commented on app/views/camps/show.html.erb
> +                <% if @camp.active? %>
Also - can you make it into a feature that can be turned on / off (in sake of borderland and others).
(add it as a setting to firestarter_settings.xml file with ability to update it using an ENV var and default - turn it off.

2017-01-24 15:22 UTC, basels commented on app/views/camps/show.html.erb
> +                <% if @camp.active? %>
Fixed

2017-01-24 15:42 UTC, merged