Send email notification after safety comments are changed
Midburn/dreams pull request #246
Opened 2017-11-25 14:13 UTC by enoodle

Fixes #245 

Created a simpler mailer class to send a notification email to the user that edited the safety comments and the Dream (camp) creator.

The email  contents can be edited in : `app/views/camp_mailer/safety_comments_updated.html.erb` (html)
or `app/views/camp_mailer/safety_comments_updated.text.erb` (text)

@LioraNaginsky @rootux

2017-11-26 03:07 UTC, rootux commented
@enoodle Looks great. Can you specify which tests did you do to make sure this works?

2017-11-26 03:08 UTC, rootux commented on app/mailers/application_mailer.rb
> +  default from: "dream@midburn.org"
@enoodle Should be "dreams@midburn.org" instead of dream

2017-11-26 03:08 UTC, rootux commented on app/mailers/camp_mailer.rb
> +         :subject => "Safety Comment Updated For Dream #{camp.name}")
Should use i18n Translation english->hebrew

2017-11-26 03:08 UTC, rootux commented on app/views/camp_mailer/safety_comments_updated.html.erb
> +    <h1>Dream Safety Comments Were Updated for <%= @camp.name %></h1>
Should use i18n Translation english->hebrew

2017-11-26 03:09 UTC, rootux commented on app/views/camp_mailer/safety_comments_updated.html.erb
> +    <p>SOME CLOSING LINE OR UNICORN!</p>
Please replace with closing line or a unicorn :)

2017-11-26 03:10 UTC, rootux requested changes

2017-11-26 03:10 UTC, rootux commented on app/views/camp_mailer/safety_comments_updated.text.erb
> +SOME CLOSING LINE OR UNICORN!
Please remove or add a closing line

2017-11-27 21:16 UTC, enoodle commented
@rootux 
> Can you specify which tests did you do to make sure this works?

I added two tests: one that makes sure that the controller can render a simple sample mail, sanity check to prevent us from breaking something in the view files. Another is a test in the camps controller spec that makes sure that when the comment file is updated we are calling the email sending function in that controller.

2017-11-28 11:14 UTC, merged